[build]
  command = "node netlify-build.js && npm run build && tsc -p tsconfig.netlify.json"
  publish = "dist/client"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY = "true"